/* ============================================================================
 * GO Fest 2026 Scavenger Hunt — event data
 * ============================================================================
 * Hunt rules encoded here:
 *   - The hunt runs TWICE: a fresh set of tasks each event day, with separate
 *     progress. Day 1 = Saturday's habitats, Day 2 = Sunday's habitats.
 *   - Each day a trainer gets exactly FOUR tasks:
 *       1. Catch 26 [species]                    (rerollable, once)
 *       2. Obtain 1 shiny [species]              (rerollable, once — catch OR trade)
 *       3. Catch 1 Mewtwo                        (fixed)
 *       4. High five your Community Ambassador   (fixed, just for fun)
 *     → two rerolls per day, four for the weekend.
 *   - Species pool: EVERY Pokémon released in Pokémon GO that isn't Legendary,
 *     Mythical, or an Ultra Beast. A species' primary type dictates which
 *     habitat time block (and therefore which day) it belongs to.
 *   - Regional exclusives that can't be caught in Boston, MA (Klefki,
 *     Kangaskhan, Mr. Mime, …) are excluded.
 *   - Tasks target whole evolutionary FAMILIES: babies, evolutions, and
 *     regional forms all count. The `line` string on each card spells that out.
 *   - A species never repeats across the weekend — day 2 draws (and all
 *     rerolls) exclude everything previously rolled.
 *
 * The SPECIES array between the GENERATED markers is produced by
 * `node tools/generate-data.mjs` from PvPoke's Pokémon GO gamemaster —
 * edit the config at the top of that script (Boston exclusions, rarity
 * overrides), rerun it, and bump CACHE_VERSION in sw.js.
 * ==========================================================================*/

const HABITATS = {
  stormfire: {
    name: "Stormfire Peaks",
    time: "10am–1pm",
    types: "Ice · Electric · Fire",
    emoji: "🌋",
    color: "#e8590c",
  },
  astral: {
    name: "Astral Tides",
    time: "1pm–4pm",
    types: "Psychic · Ghost · Water",
    emoji: "🌊",
    color: "#7048e8",
  },
  dragonflight: {
    name: "Dragonflight Summit",
    time: "4pm–7pm",
    types: "Flying · Rock · Dragon",
    emoji: "🐉",
    color: "#0c8599",
  },
  earthforged: {
    name: "Earthforged Domain",
    time: "10am–1pm",
    types: "Ground · Steel · Normal",
    emoji: "⛏️",
    color: "#a87900",
  },
  verdant: {
    name: "Verdant Anomaly",
    time: "1pm–4pm",
    types: "Poison · Bug · Grass",
    emoji: "🌿",
    color: "#2f9e44",
  },
  twilight: {
    name: "Twilight Battlefield",
    time: "4pm–7pm",
    types: "Dark · Fairy · Fighting",
    emoji: "🌙",
    color: "#c2255c",
  },
};

// The two event days. Species tasks for a day draw only from its habitats.
const DAYS = {
  day1: {
    label: "Saturday",
    date: "Jul 11",
    habitats: ["stormfire", "astral", "dragonflight"],
  },
  day2: {
    label: "Sunday",
    date: "Jul 12",
    habitats: ["earthforged", "verdant", "twilight"],
  },
};

// Task 1: "Catch 26 [species]". Drawn from these rarity tiers only — catching
// 26 of a pseudo-legendary line would be miserable even at GO Fest.
const CATCH_TASK_COUNT = 26;
const CATCH_TASK_TIERS = ["common", "uncommon"];

// Task 2: "Obtain 1 shiny [species]". One is all it takes, so any tier goes.
const SHINY_TASK_TIERS = ["common", "uncommon", "rare"];

// Tasks 3 & 4, identical for every trainer every day.
const MEWTWO_TASK = {
  type: "mewtwo",
  text: "Catch 1 Mewtwo",
  note: "The exception to the wild-spawn rule! Any Mewtwo counts, including one caught after a Mega Mewtwo X or Y Super Mega Raid.",
};

const HIGHFIVE_TASK = {
  type: "highfive",
  text: "High five your Community Ambassador",
  note: "That's it. That's the task. 🖐️",
};

const SPECIES = [
// BEGIN GENERATED SPECIES (tools/generate-data.mjs) — do not edit by hand
  { name: "Bulbasaur", habitat: "verdant", tier: "common", line: "Bulbasaur, Ivysaur & Venusaur" },
  { name: "Charmander", habitat: "stormfire", tier: "common", line: "Charmander, Charmeleon & Charizard" },
  { name: "Squirtle", habitat: "astral", tier: "common", line: "Squirtle, Wartortle & Blastoise" },
  { name: "Caterpie", habitat: "verdant", tier: "common", line: "Caterpie, Metapod & Butterfree" },
  { name: "Weedle", habitat: "verdant", tier: "common", line: "Weedle, Kakuna & Beedrill" },
  { name: "Pidgey", habitat: "earthforged", tier: "common", line: "Pidgey, Pidgeotto & Pidgeot" },
  { name: "Rattata", habitat: "earthforged", tier: "common", line: "Rattata & Raticate — any form" },
  { name: "Spearow", habitat: "earthforged", tier: "common", line: "Spearow & Fearow" },
  { name: "Ekans", habitat: "verdant", tier: "common", line: "Ekans & Arbok" },
  { name: "Pikachu", habitat: "stormfire", tier: "common", line: "Pikachu, Raichu & Pichu — any form" },
  { name: "Sandshrew", habitat: "earthforged", tier: "common", line: "Sandshrew & Sandslash — any form" },
  { name: "Nidoran Female", habitat: "verdant", tier: "common", line: "Nidoran Female, Nidorina & Nidoqueen" },
  { name: "Nidoran Male", habitat: "verdant", tier: "common", line: "Nidoran Male, Nidorino & Nidoking" },
  { name: "Clefairy", habitat: "twilight", tier: "common", line: "Clefairy, Clefable & Cleffa" },
  { name: "Vulpix", habitat: "stormfire", tier: "common", line: "Vulpix & Ninetales — any form" },
  { name: "Jigglypuff", habitat: "earthforged", tier: "common", line: "Jigglypuff, Wigglytuff & Igglybuff" },
  { name: "Zubat", habitat: "verdant", tier: "common", line: "Zubat, Golbat & Crobat" },
  { name: "Oddish", habitat: "verdant", tier: "common", line: "Oddish, Gloom, Vileplume & Bellossom" },
  { name: "Paras", habitat: "verdant", tier: "common", line: "Paras & Parasect" },
  { name: "Venonat", habitat: "verdant", tier: "common", line: "Venonat & Venomoth" },
  { name: "Diglett", habitat: "earthforged", tier: "common", line: "Diglett & Dugtrio — any form" },
  { name: "Meowth", habitat: "earthforged", tier: "common", line: "Meowth, Persian & Perrserker — any form" },
  { name: "Psyduck", habitat: "astral", tier: "common", line: "Psyduck & Golduck" },
  { name: "Mankey", habitat: "twilight", tier: "common", line: "Mankey, Primeape & Annihilape" },
  { name: "Growlithe", habitat: "stormfire", tier: "common", line: "Growlithe & Arcanine — any form" },
  { name: "Poliwag", habitat: "astral", tier: "common", line: "Poliwag, Poliwhirl, Poliwrath & Politoed" },
  { name: "Abra", habitat: "astral", tier: "common", line: "Abra, Kadabra & Alakazam" },
  { name: "Machop", habitat: "twilight", tier: "common", line: "Machop, Machoke & Machamp" },
  { name: "Bellsprout", habitat: "verdant", tier: "common", line: "Bellsprout, Weepinbell & Victreebel" },
  { name: "Tentacool", habitat: "astral", tier: "common", line: "Tentacool & Tentacruel" },
  { name: "Geodude", habitat: "dragonflight", tier: "common", line: "Geodude, Graveler & Golem — any form" },
  { name: "Ponyta", habitat: "stormfire", tier: "common", line: "Ponyta & Rapidash — any form" },
  { name: "Slowpoke", habitat: "astral", tier: "common", line: "Slowpoke, Slowbro & Slowking — any form" },
  { name: "Magnemite", habitat: "stormfire", tier: "common", line: "Magnemite, Magneton & Magnezone" },
  { name: "Doduo", habitat: "earthforged", tier: "common", line: "Doduo & Dodrio" },
  { name: "Seel", habitat: "astral", tier: "common", line: "Seel & Dewgong" },
  { name: "Grimer", habitat: "verdant", tier: "common", line: "Grimer & Muk — any form" },
  { name: "Shellder", habitat: "astral", tier: "common", line: "Shellder & Cloyster" },
  { name: "Gastly", habitat: "astral", tier: "common", line: "Gastly, Haunter & Gengar" },
  { name: "Onix", habitat: "dragonflight", tier: "common", line: "Onix & Steelix" },
  { name: "Drowzee", habitat: "astral", tier: "common", line: "Drowzee & Hypno" },
  { name: "Krabby", habitat: "astral", tier: "common", line: "Krabby & Kingler" },
  { name: "Voltorb", habitat: "stormfire", tier: "common", line: "Voltorb & Electrode — any form" },
  { name: "Exeggcute", habitat: "verdant", tier: "common", line: "Exeggcute & Exeggutor — any form" },
  { name: "Cubone", habitat: "earthforged", tier: "common", line: "Cubone & Marowak — any form" },
  { name: "Hitmonlee", habitat: "twilight", tier: "common", line: "Hitmonlee, Hitmonchan, Tyrogue & Hitmontop" },
  { name: "Lickitung", habitat: "earthforged", tier: "common", line: "Lickitung & Lickilicky" },
  { name: "Koffing", habitat: "verdant", tier: "common", line: "Koffing & Weezing — any form" },
  { name: "Rhyhorn", habitat: "earthforged", tier: "common", line: "Rhyhorn, Rhydon & Rhyperior" },
  { name: "Chansey", habitat: "earthforged", tier: "rare", line: "Chansey, Blissey & Happiny" },
  { name: "Tangela", habitat: "verdant", tier: "common", line: "Tangela & Tangrowth" },
  { name: "Horsea", habitat: "astral", tier: "common", line: "Horsea, Seadra & Kingdra" },
  { name: "Goldeen", habitat: "astral", tier: "common", line: "Goldeen & Seaking" },
  { name: "Staryu", habitat: "astral", tier: "common", line: "Staryu & Starmie" },
  { name: "Scyther", habitat: "verdant", tier: "common", line: "Scyther, Scizor & Kleavor" },
  { name: "Jynx", habitat: "stormfire", tier: "common", line: "Jynx & Smoochum" },
  { name: "Electabuzz", habitat: "stormfire", tier: "common", line: "Electabuzz, Elekid & Electivire" },
  { name: "Magmar", habitat: "stormfire", tier: "common", line: "Magmar, Magby & Magmortar" },
  { name: "Pinsir", habitat: "verdant", tier: "uncommon", line: "Pinsir" },
  { name: "Tauros", habitat: "earthforged", tier: "uncommon", line: "Tauros — any form" },
  { name: "Magikarp", habitat: "astral", tier: "common", line: "Magikarp & Gyarados" },
  { name: "Lapras", habitat: "astral", tier: "uncommon", line: "Lapras" },
  { name: "Ditto", habitat: "earthforged", tier: "rare", line: "Ditto" },
  { name: "Eevee", habitat: "earthforged", tier: "common", line: "Eevee, Vaporeon, Jolteon, Flareon, Espeon, Umbreon, Leafeon, Glaceon & Sylveon" },
  { name: "Porygon", habitat: "earthforged", tier: "common", line: "Porygon, Porygon2 & Porygon-Z" },
  { name: "Omanyte", habitat: "dragonflight", tier: "uncommon", line: "Omanyte & Omastar" },
  { name: "Kabuto", habitat: "dragonflight", tier: "uncommon", line: "Kabuto & Kabutops" },
  { name: "Aerodactyl", habitat: "dragonflight", tier: "uncommon", line: "Aerodactyl" },
  { name: "Snorlax", habitat: "earthforged", tier: "uncommon", line: "Snorlax & Munchlax" },
  { name: "Dratini", habitat: "dragonflight", tier: "rare", line: "Dratini, Dragonair & Dragonite" },
  { name: "Chikorita", habitat: "verdant", tier: "common", line: "Chikorita, Bayleef & Meganium" },
  { name: "Cyndaquil", habitat: "stormfire", tier: "common", line: "Cyndaquil, Quilava & Typhlosion — any form" },
  { name: "Totodile", habitat: "astral", tier: "common", line: "Totodile, Croconaw & Feraligatr" },
  { name: "Sentret", habitat: "earthforged", tier: "common", line: "Sentret & Furret" },
  { name: "Hoothoot", habitat: "earthforged", tier: "common", line: "Hoothoot & Noctowl" },
  { name: "Ledyba", habitat: "verdant", tier: "common", line: "Ledyba & Ledian" },
  { name: "Spinarak", habitat: "verdant", tier: "common", line: "Spinarak & Ariados" },
  { name: "Chinchou", habitat: "astral", tier: "common", line: "Chinchou & Lanturn" },
  { name: "Togetic", habitat: "twilight", tier: "rare", line: "Togepi, Togetic & Togekiss" },
  { name: "Natu", habitat: "astral", tier: "common", line: "Natu & Xatu" },
  { name: "Mareep", habitat: "stormfire", tier: "common", line: "Mareep, Flaaffy & Ampharos" },
  { name: "Marill", habitat: "astral", tier: "common", line: "Marill, Azumarill & Azurill" },
  { name: "Sudowoodo", habitat: "dragonflight", tier: "common", line: "Sudowoodo & Bonsly" },
  { name: "Hoppip", habitat: "verdant", tier: "common", line: "Hoppip, Skiploom & Jumpluff" },
  { name: "Aipom", habitat: "earthforged", tier: "common", line: "Aipom & Ambipom" },
  { name: "Sunkern", habitat: "verdant", tier: "common", line: "Sunkern & Sunflora" },
  { name: "Yanma", habitat: "verdant", tier: "common", line: "Yanma & Yanmega" },
  { name: "Wooper", habitat: "astral", tier: "common", line: "Wooper & Quagsire — any form" },
  { name: "Murkrow", habitat: "twilight", tier: "common", line: "Murkrow & Honchkrow" },
  { name: "Misdreavus", habitat: "astral", tier: "common", line: "Misdreavus & Mismagius" },
  { name: "Unown", habitat: "astral", tier: "rare", line: "Unown" },
  { name: "Wobbuffet", habitat: "astral", tier: "common", line: "Wobbuffet & Wynaut" },
  { name: "Girafarig", habitat: "earthforged", tier: "uncommon", line: "Girafarig" },
  { name: "Pineco", habitat: "verdant", tier: "common", line: "Pineco & Forretress" },
  { name: "Dunsparce", habitat: "earthforged", tier: "common", line: "Dunsparce & Dudunsparce" },
  { name: "Gligar", habitat: "earthforged", tier: "common", line: "Gligar & Gliscor" },
  { name: "Snubbull", habitat: "twilight", tier: "common", line: "Snubbull & Granbull" },
  { name: "Qwilfish", habitat: "astral", tier: "common", line: "Qwilfish & Overqwil — any form" },
  { name: "Shuckle", habitat: "verdant", tier: "uncommon", line: "Shuckle" },
  { name: "Sneasel", habitat: "twilight", tier: "common", line: "Sneasel, Weavile & Sneasler — any form" },
  { name: "Teddiursa", habitat: "earthforged", tier: "common", line: "Teddiursa, Ursaring & Ursaluna" },
  { name: "Slugma", habitat: "stormfire", tier: "common", line: "Slugma & Magcargo" },
  { name: "Swinub", habitat: "stormfire", tier: "common", line: "Swinub, Piloswine & Mamoswine" },
  { name: "Remoraid", habitat: "astral", tier: "common", line: "Remoraid & Octillery" },
  { name: "Delibird", habitat: "stormfire", tier: "uncommon", line: "Delibird" },
  { name: "Mantine", habitat: "astral", tier: "common", line: "Mantine & Mantyke" },
  { name: "Skarmory", habitat: "earthforged", tier: "uncommon", line: "Skarmory" },
  { name: "Houndour", habitat: "twilight", tier: "common", line: "Houndour & Houndoom" },
  { name: "Phanpy", habitat: "earthforged", tier: "common", line: "Phanpy & Donphan" },
  { name: "Stantler", habitat: "earthforged", tier: "common", line: "Stantler & Wyrdeer" },
  { name: "Smeargle", habitat: "earthforged", tier: "uncommon", line: "Smeargle" },
  { name: "Miltank", habitat: "earthforged", tier: "uncommon", line: "Miltank" },
  { name: "Larvitar", habitat: "dragonflight", tier: "rare", line: "Larvitar, Pupitar & Tyranitar" },
  { name: "Treecko", habitat: "verdant", tier: "common", line: "Treecko, Grovyle & Sceptile" },
  { name: "Torchic", habitat: "stormfire", tier: "common", line: "Torchic, Combusken & Blaziken" },
  { name: "Mudkip", habitat: "astral", tier: "common", line: "Mudkip, Marshtomp & Swampert" },
  { name: "Poochyena", habitat: "twilight", tier: "common", line: "Poochyena & Mightyena" },
  { name: "Zigzagoon", habitat: "earthforged", tier: "common", line: "Zigzagoon, Linoone & Obstagoon — any form" },
  { name: "Wurmple", habitat: "verdant", tier: "common", line: "Wurmple, Silcoon, Beautifly, Cascoon & Dustox" },
  { name: "Lotad", habitat: "astral", tier: "common", line: "Lotad, Lombre & Ludicolo" },
  { name: "Seedot", habitat: "verdant", tier: "common", line: "Seedot, Nuzleaf & Shiftry" },
  { name: "Taillow", habitat: "earthforged", tier: "common", line: "Taillow & Swellow" },
  { name: "Wingull", habitat: "astral", tier: "common", line: "Wingull & Pelipper" },
  { name: "Ralts", habitat: "astral", tier: "common", line: "Ralts, Kirlia, Gardevoir & Gallade" },
  { name: "Surskit", habitat: "verdant", tier: "common", line: "Surskit & Masquerain" },
  { name: "Shroomish", habitat: "verdant", tier: "common", line: "Shroomish & Breloom" },
  { name: "Slakoth", habitat: "earthforged", tier: "common", line: "Slakoth, Vigoroth & Slaking" },
  { name: "Nincada", habitat: "verdant", tier: "common", line: "Nincada & Ninjask" },
  { name: "Whismur", habitat: "earthforged", tier: "common", line: "Whismur, Loudred & Exploud" },
  { name: "Makuhita", habitat: "twilight", tier: "common", line: "Makuhita & Hariyama" },
  { name: "Nosepass", habitat: "dragonflight", tier: "common", line: "Nosepass & Probopass" },
  { name: "Skitty", habitat: "earthforged", tier: "common", line: "Skitty & Delcatty" },
  { name: "Sableye", habitat: "twilight", tier: "uncommon", line: "Sableye" },
  { name: "Mawile", habitat: "earthforged", tier: "uncommon", line: "Mawile" },
  { name: "Aron", habitat: "earthforged", tier: "common", line: "Aron, Lairon & Aggron" },
  { name: "Meditite", habitat: "twilight", tier: "common", line: "Meditite & Medicham" },
  { name: "Electrike", habitat: "stormfire", tier: "common", line: "Electrike & Manectric" },
  { name: "Plusle", habitat: "stormfire", tier: "uncommon", line: "Plusle" },
  { name: "Minun", habitat: "stormfire", tier: "uncommon", line: "Minun" },
  { name: "Illumise", habitat: "verdant", tier: "uncommon", line: "Illumise" },
  { name: "Roselia", habitat: "verdant", tier: "common", line: "Roselia, Budew & Roserade" },
  { name: "Gulpin", habitat: "verdant", tier: "common", line: "Gulpin & Swalot" },
  { name: "Carvanha", habitat: "astral", tier: "common", line: "Carvanha & Sharpedo" },
  { name: "Wailmer", habitat: "astral", tier: "common", line: "Wailmer & Wailord" },
  { name: "Numel", habitat: "stormfire", tier: "common", line: "Numel & Camerupt" },
  { name: "Spoink", habitat: "astral", tier: "common", line: "Spoink & Grumpig" },
  { name: "Spinda", habitat: "earthforged", tier: "uncommon", line: "Spinda" },
  { name: "Trapinch", habitat: "earthforged", tier: "common", line: "Trapinch, Vibrava & Flygon" },
  { name: "Cacnea", habitat: "verdant", tier: "common", line: "Cacnea & Cacturne" },
  { name: "Swablu", habitat: "earthforged", tier: "common", line: "Swablu & Altaria" },
  { name: "Seviper", habitat: "verdant", tier: "uncommon", line: "Seviper" },
  { name: "Lunatone", habitat: "dragonflight", tier: "uncommon", line: "Lunatone" },
  { name: "Barboach", habitat: "astral", tier: "common", line: "Barboach & Whiscash" },
  { name: "Corphish", habitat: "astral", tier: "common", line: "Corphish & Crawdaunt" },
  { name: "Baltoy", habitat: "earthforged", tier: "common", line: "Baltoy & Claydol" },
  { name: "Lileep", habitat: "dragonflight", tier: "uncommon", line: "Lileep & Cradily" },
  { name: "Anorith", habitat: "dragonflight", tier: "uncommon", line: "Anorith & Armaldo" },
  { name: "Feebas", habitat: "astral", tier: "common", line: "Feebas & Milotic" },
  { name: "Castform", habitat: "earthforged", tier: "uncommon", line: "Castform" },
  { name: "Kecleon", habitat: "earthforged", tier: "uncommon", line: "Kecleon" },
  { name: "Shuppet", habitat: "astral", tier: "common", line: "Shuppet & Banette" },
  { name: "Duskull", habitat: "astral", tier: "common", line: "Duskull, Dusclops & Dusknoir" },
  { name: "Chimecho", habitat: "astral", tier: "common", line: "Chimecho & Chingling" },
  { name: "Absol", habitat: "twilight", tier: "uncommon", line: "Absol" },
  { name: "Snorunt", habitat: "stormfire", tier: "common", line: "Snorunt, Glalie & Froslass" },
  { name: "Spheal", habitat: "stormfire", tier: "common", line: "Spheal, Sealeo & Walrein" },
  { name: "Clamperl", habitat: "astral", tier: "common", line: "Clamperl, Huntail & Gorebyss" },
  { name: "Luvdisc", habitat: "astral", tier: "uncommon", line: "Luvdisc" },
  { name: "Bagon", habitat: "dragonflight", tier: "rare", line: "Bagon, Shelgon & Salamence" },
  { name: "Beldum", habitat: "earthforged", tier: "rare", line: "Beldum, Metang & Metagross" },
  { name: "Turtwig", habitat: "verdant", tier: "common", line: "Turtwig, Grotle & Torterra" },
  { name: "Chimchar", habitat: "stormfire", tier: "common", line: "Chimchar, Monferno & Infernape" },
  { name: "Piplup", habitat: "astral", tier: "common", line: "Piplup, Prinplup & Empoleon" },
  { name: "Starly", habitat: "earthforged", tier: "common", line: "Starly, Staravia & Staraptor" },
  { name: "Bidoof", habitat: "earthforged", tier: "common", line: "Bidoof & Bibarel" },
  { name: "Kricketot", habitat: "verdant", tier: "common", line: "Kricketot & Kricketune" },
  { name: "Shinx", habitat: "stormfire", tier: "common", line: "Shinx, Luxio & Luxray" },
  { name: "Cranidos", habitat: "dragonflight", tier: "uncommon", line: "Cranidos & Rampardos" },
  { name: "Shieldon", habitat: "dragonflight", tier: "uncommon", line: "Shieldon & Bastiodon" },
  { name: "Burmy", habitat: "verdant", tier: "common", line: "Burmy, Wormadam & Mothim" },
  { name: "Combee", habitat: "verdant", tier: "common", line: "Combee & Vespiquen" },
  { name: "Buizel", habitat: "astral", tier: "common", line: "Buizel & Floatzel" },
  { name: "Cherubi", habitat: "verdant", tier: "common", line: "Cherubi & Cherrim" },
  { name: "Shellos", habitat: "astral", tier: "uncommon", line: "Shellos" },
  { name: "Gastrodon", habitat: "astral", tier: "uncommon", line: "Gastrodon" },
  { name: "Drifloon", habitat: "astral", tier: "common", line: "Drifloon & Drifblim" },
  { name: "Buneary", habitat: "earthforged", tier: "common", line: "Buneary & Lopunny" },
  { name: "Glameow", habitat: "earthforged", tier: "common", line: "Glameow & Purugly" },
  { name: "Stunky", habitat: "verdant", tier: "common", line: "Stunky & Skuntank" },
  { name: "Bronzor", habitat: "earthforged", tier: "common", line: "Bronzor & Bronzong" },
  { name: "Spiritomb", habitat: "astral", tier: "uncommon", line: "Spiritomb" },
  { name: "Gible", habitat: "dragonflight", tier: "rare", line: "Gible, Gabite & Garchomp" },
  { name: "Lucario", habitat: "twilight", tier: "rare", line: "Riolu & Lucario" },
  { name: "Hippopotas", habitat: "earthforged", tier: "common", line: "Hippopotas & Hippowdon" },
  { name: "Skorupi", habitat: "verdant", tier: "common", line: "Skorupi & Drapion" },
  { name: "Croagunk", habitat: "verdant", tier: "common", line: "Croagunk & Toxicroak" },
  { name: "Finneon", habitat: "astral", tier: "common", line: "Finneon & Lumineon" },
  { name: "Snover", habitat: "verdant", tier: "common", line: "Snover & Abomasnow" },
  { name: "Rotom", habitat: "stormfire", tier: "rare", line: "Rotom" },
  { name: "Snivy", habitat: "verdant", tier: "common", line: "Snivy, Servine & Serperior" },
  { name: "Tepig", habitat: "stormfire", tier: "common", line: "Tepig, Pignite & Emboar" },
  { name: "Oshawott", habitat: "astral", tier: "common", line: "Oshawott, Dewott & Samurott — any form" },
  { name: "Patrat", habitat: "earthforged", tier: "common", line: "Patrat & Watchog" },
  { name: "Lillipup", habitat: "earthforged", tier: "common", line: "Lillipup, Herdier & Stoutland" },
  { name: "Purrloin", habitat: "twilight", tier: "common", line: "Purrloin & Liepard" },
  { name: "Simisage", habitat: "verdant", tier: "uncommon", line: "Simisage" },
  { name: "Simisear", habitat: "stormfire", tier: "uncommon", line: "Simisear" },
  { name: "Panpour", habitat: "astral", tier: "common", line: "Panpour & Simipour" },
  { name: "Munna", habitat: "astral", tier: "common", line: "Munna & Musharna" },
  { name: "Pidove", habitat: "earthforged", tier: "common", line: "Pidove, Tranquill & Unfezant" },
  { name: "Blitzle", habitat: "stormfire", tier: "common", line: "Blitzle & Zebstrika" },
  { name: "Roggenrola", habitat: "dragonflight", tier: "common", line: "Roggenrola, Boldore & Gigalith" },
  { name: "Woobat", habitat: "astral", tier: "common", line: "Woobat & Swoobat" },
  { name: "Drilbur", habitat: "earthforged", tier: "common", line: "Drilbur & Excadrill" },
  { name: "Audino", habitat: "earthforged", tier: "uncommon", line: "Audino" },
  { name: "Timburr", habitat: "twilight", tier: "common", line: "Timburr, Gurdurr & Conkeldurr" },
  { name: "Tympole", habitat: "astral", tier: "common", line: "Tympole, Palpitoad & Seismitoad" },
  { name: "Throh", habitat: "twilight", tier: "uncommon", line: "Throh" },
  { name: "Sawk", habitat: "twilight", tier: "uncommon", line: "Sawk" },
  { name: "Sewaddle", habitat: "verdant", tier: "common", line: "Sewaddle, Swadloon & Leavanny" },
  { name: "Venipede", habitat: "verdant", tier: "common", line: "Venipede, Whirlipede & Scolipede" },
  { name: "Cottonee", habitat: "verdant", tier: "common", line: "Cottonee & Whimsicott" },
  { name: "Petilil", habitat: "verdant", tier: "common", line: "Petilil & Lilligant — any form" },
  { name: "Basculin", habitat: "astral", tier: "uncommon", line: "Basculin" },
  { name: "Sandile", habitat: "earthforged", tier: "common", line: "Sandile, Krokorok & Krookodile" },
  { name: "Darumaka", habitat: "stormfire", tier: "common", line: "Darumaka & Darmanitan — any form" },
  { name: "Dwebble", habitat: "verdant", tier: "common", line: "Dwebble & Crustle" },
  { name: "Scraggy", habitat: "twilight", tier: "common", line: "Scraggy & Scrafty" },
  { name: "Yamask", habitat: "astral", tier: "common", line: "Yamask, Cofagrigus & Runerigus — any form" },
  { name: "Tirtouga", habitat: "astral", tier: "uncommon", line: "Tirtouga & Carracosta" },
  { name: "Archen", habitat: "dragonflight", tier: "uncommon", line: "Archen & Archeops" },
  { name: "Trubbish", habitat: "verdant", tier: "common", line: "Trubbish & Garbodor" },
  { name: "Zorua", habitat: "twilight", tier: "common", line: "Zorua & Zoroark — any form" },
  { name: "Minccino", habitat: "earthforged", tier: "common", line: "Minccino & Cinccino" },
  { name: "Gothita", habitat: "astral", tier: "common", line: "Gothita, Gothorita & Gothitelle" },
  { name: "Solosis", habitat: "astral", tier: "common", line: "Solosis, Duosion & Reuniclus" },
  { name: "Ducklett", habitat: "astral", tier: "common", line: "Ducklett & Swanna" },
  { name: "Vanillite", habitat: "stormfire", tier: "common", line: "Vanillite, Vanillish & Vanilluxe" },
  { name: "Deerling", habitat: "earthforged", tier: "common", line: "Deerling & Sawsbuck" },
  { name: "Emolga", habitat: "stormfire", tier: "uncommon", line: "Emolga" },
  { name: "Karrablast", habitat: "verdant", tier: "common", line: "Karrablast & Escavalier" },
  { name: "Foongus", habitat: "verdant", tier: "common", line: "Foongus & Amoonguss" },
  { name: "Frillish", habitat: "astral", tier: "common", line: "Frillish & Jellicent" },
  { name: "Alomomola", habitat: "astral", tier: "uncommon", line: "Alomomola" },
  { name: "Joltik", habitat: "verdant", tier: "common", line: "Joltik & Galvantula" },
  { name: "Ferroseed", habitat: "verdant", tier: "common", line: "Ferroseed & Ferrothorn" },
  { name: "Klink", habitat: "earthforged", tier: "common", line: "Klink, Klang & Klinklang" },
  { name: "Tynamo", habitat: "stormfire", tier: "common", line: "Tynamo, Eelektrik & Eelektross" },
  { name: "Elgyem", habitat: "astral", tier: "common", line: "Elgyem & Beheeyem" },
  { name: "Litwick", habitat: "astral", tier: "common", line: "Litwick, Lampent & Chandelure" },
  { name: "Axew", habitat: "dragonflight", tier: "rare", line: "Axew, Fraxure & Haxorus" },
  { name: "Cubchoo", habitat: "stormfire", tier: "common", line: "Cubchoo & Beartic" },
  { name: "Cryogonal", habitat: "stormfire", tier: "uncommon", line: "Cryogonal" },
  { name: "Shelmet", habitat: "verdant", tier: "common", line: "Shelmet & Accelgor" },
  { name: "Stunfisk", habitat: "earthforged", tier: "uncommon", line: "Stunfisk — any form" },
  { name: "Mienfoo", habitat: "twilight", tier: "common", line: "Mienfoo & Mienshao" },
  { name: "Druddigon", habitat: "dragonflight", tier: "uncommon", line: "Druddigon" },
  { name: "Golett", habitat: "earthforged", tier: "common", line: "Golett & Golurk" },
  { name: "Pawniard", habitat: "twilight", tier: "common", line: "Pawniard, Bisharp & Kingambit" },
  { name: "Rufflet", habitat: "earthforged", tier: "common", line: "Rufflet & Braviary — any form" },
  { name: "Vullaby", habitat: "twilight", tier: "common", line: "Vullaby & Mandibuzz" },
  { name: "Heatmor", habitat: "stormfire", tier: "uncommon", line: "Heatmor" },
  { name: "Deino", habitat: "twilight", tier: "rare", line: "Deino, Zweilous & Hydreigon" },
  { name: "Larvesta", habitat: "verdant", tier: "rare", line: "Larvesta & Volcarona" },
  { name: "Chespin", habitat: "verdant", tier: "common", line: "Chespin, Quilladin & Chesnaught" },
  { name: "Fennekin", habitat: "stormfire", tier: "common", line: "Fennekin, Braixen & Delphox" },
  { name: "Froakie", habitat: "astral", tier: "common", line: "Froakie, Frogadier & Greninja" },
  { name: "Bunnelby", habitat: "earthforged", tier: "common", line: "Bunnelby & Diggersby" },
  { name: "Fletchling", habitat: "earthforged", tier: "common", line: "Fletchling, Fletchinder & Talonflame" },
  { name: "Scatterbug", habitat: "verdant", tier: "common", line: "Scatterbug & Vivillon" },
  { name: "Litleo", habitat: "stormfire", tier: "common", line: "Litleo & Pyroar" },
  { name: "Flabebe", habitat: "twilight", tier: "common", line: "Flabebe, Floette & Florges" },
  { name: "Skiddo", habitat: "verdant", tier: "common", line: "Skiddo & Gogoat" },
  { name: "Pancham", habitat: "twilight", tier: "common", line: "Pancham & Pangoro" },
  { name: "Furfrou", habitat: "earthforged", tier: "uncommon", line: "Furfrou" },
  { name: "Espurr", habitat: "astral", tier: "common", line: "Espurr & Meowstic" },
  { name: "Honedge", habitat: "earthforged", tier: "common", line: "Honedge, Doublade & Aegislash" },
  { name: "Spritzee", habitat: "twilight", tier: "common", line: "Spritzee & Aromatisse" },
  { name: "Swirlix", habitat: "twilight", tier: "common", line: "Swirlix & Slurpuff" },
  { name: "Inkay", habitat: "twilight", tier: "common", line: "Inkay & Malamar" },
  { name: "Binacle", habitat: "dragonflight", tier: "common", line: "Binacle & Barbaracle" },
  { name: "Skrelp", habitat: "verdant", tier: "common", line: "Skrelp & Dragalge" },
  { name: "Clauncher", habitat: "astral", tier: "common", line: "Clauncher & Clawitzer" },
  { name: "Helioptile", habitat: "stormfire", tier: "common", line: "Helioptile & Heliolisk" },
  { name: "Tyrunt", habitat: "dragonflight", tier: "uncommon", line: "Tyrunt & Tyrantrum" },
  { name: "Amaura", habitat: "dragonflight", tier: "uncommon", line: "Amaura & Aurorus" },
  { name: "Dedenne", habitat: "stormfire", tier: "uncommon", line: "Dedenne" },
  { name: "Carbink", habitat: "dragonflight", tier: "uncommon", line: "Carbink" },
  { name: "Goomy", habitat: "dragonflight", tier: "rare", line: "Goomy, Sliggoo & Goodra" },
  { name: "Phantump", habitat: "astral", tier: "common", line: "Phantump & Trevenant" },
  { name: "Pumpkaboo", habitat: "astral", tier: "common", line: "Pumpkaboo & Gourgeist" },
  { name: "Bergmite", habitat: "stormfire", tier: "common", line: "Bergmite & Avalugg — any form" },
  { name: "Noibat", habitat: "dragonflight", tier: "rare", line: "Noibat & Noivern" },
  { name: "Rowlet", habitat: "verdant", tier: "common", line: "Rowlet, Dartrix & Decidueye" },
  { name: "Litten", habitat: "stormfire", tier: "common", line: "Litten, Torracat & Incineroar" },
  { name: "Popplio", habitat: "astral", tier: "common", line: "Popplio, Brionne & Primarina" },
  { name: "Pikipek", habitat: "earthforged", tier: "common", line: "Pikipek, Trumbeak & Toucannon" },
  { name: "Yungoos", habitat: "earthforged", tier: "common", line: "Yungoos & Gumshoos" },
  { name: "Grubbin", habitat: "verdant", tier: "common", line: "Grubbin, Charjabug & Vikavolt" },
  { name: "Crabrawler", habitat: "twilight", tier: "common", line: "Crabrawler & Crabominable" },
  { name: "Oricorio", habitat: "astral", tier: "uncommon", line: "Oricorio" },
  { name: "Cutiefly", habitat: "verdant", tier: "common", line: "Cutiefly & Ribombee" },
  { name: "Rockruff", habitat: "dragonflight", tier: "common", line: "Rockruff & Lycanroc" },
  { name: "Mareanie", habitat: "verdant", tier: "common", line: "Mareanie & Toxapex" },
  { name: "Mudbray", habitat: "earthforged", tier: "common", line: "Mudbray & Mudsdale" },
  { name: "Dewpider", habitat: "astral", tier: "common", line: "Dewpider & Araquanid" },
  { name: "Fomantis", habitat: "verdant", tier: "common", line: "Fomantis & Lurantis" },
  { name: "Morelull", habitat: "verdant", tier: "common", line: "Morelull & Shiinotic" },
  { name: "Salandit", habitat: "verdant", tier: "common", line: "Salandit & Salazzle" },
  { name: "Stufful", habitat: "earthforged", tier: "common", line: "Stufful & Bewear" },
  { name: "Bounsweet", habitat: "verdant", tier: "common", line: "Bounsweet, Steenee & Tsareena" },
  { name: "Oranguru", habitat: "earthforged", tier: "uncommon", line: "Oranguru" },
  { name: "Passimian", habitat: "twilight", tier: "uncommon", line: "Passimian" },
  { name: "Wimpod", habitat: "verdant", tier: "common", line: "Wimpod & Golisopod" },
  { name: "Sandygast", habitat: "astral", tier: "common", line: "Sandygast & Palossand" },
  { name: "Komala", habitat: "earthforged", tier: "uncommon", line: "Komala" },
  { name: "Turtonator", habitat: "stormfire", tier: "uncommon", line: "Turtonator" },
  { name: "Togedemaru", habitat: "stormfire", tier: "uncommon", line: "Togedemaru" },
  { name: "Mimikyu", habitat: "astral", tier: "uncommon", line: "Mimikyu" },
  { name: "Bruxish", habitat: "astral", tier: "uncommon", line: "Bruxish" },
  { name: "Drampa", habitat: "earthforged", tier: "uncommon", line: "Drampa" },
  { name: "Dhelmise", habitat: "astral", tier: "uncommon", line: "Dhelmise" },
  { name: "Jangmo-o", habitat: "dragonflight", tier: "rare", line: "Jangmo-o, Hakamo-o & Kommo-o" },
  { name: "Grookey", habitat: "verdant", tier: "common", line: "Grookey, Thwackey & Rillaboom" },
  { name: "Scorbunny", habitat: "stormfire", tier: "common", line: "Scorbunny, Raboot & Cinderace" },
  { name: "Sobble", habitat: "astral", tier: "common", line: "Sobble, Drizzile & Inteleon" },
  { name: "Skwovet", habitat: "earthforged", tier: "common", line: "Skwovet & Greedent" },
  { name: "Rookidee", habitat: "dragonflight", tier: "common", line: "Rookidee, Corvisquire & Corviknight" },
  { name: "Blipbug", habitat: "verdant", tier: "common", line: "Blipbug, Dottler & Orbeetle" },
  { name: "Nickit", habitat: "twilight", tier: "common", line: "Nickit & Thievul" },
  { name: "Gossifleur", habitat: "verdant", tier: "common", line: "Gossifleur & Eldegoss" },
  { name: "Wooloo", habitat: "earthforged", tier: "common", line: "Wooloo & Dubwool" },
  { name: "Yamper", habitat: "stormfire", tier: "common", line: "Yamper & Boltund" },
  { name: "Rolycoly", habitat: "dragonflight", tier: "common", line: "Rolycoly, Carkol & Coalossal" },
  { name: "Applin", habitat: "verdant", tier: "common", line: "Applin, Flapple, Appletun, Dipplin & Hydrapple" },
  { name: "Silicobra", habitat: "earthforged", tier: "common", line: "Silicobra & Sandaconda" },
  { name: "Toxtricity", habitat: "stormfire", tier: "common", line: "Toxel & Toxtricity" },
  { name: "Sizzlipede", habitat: "stormfire", tier: "common", line: "Sizzlipede & Centiskorch" },
  { name: "Clobbopus", habitat: "twilight", tier: "common", line: "Clobbopus & Grapploct" },
  { name: "Sinistea", habitat: "astral", tier: "common", line: "Sinistea & Polteageist" },
  { name: "Hatenna", habitat: "astral", tier: "common", line: "Hatenna, Hattrem & Hatterene" },
  { name: "Impidimp", habitat: "twilight", tier: "common", line: "Impidimp, Morgrem & Grimmsnarl" },
  { name: "Cursola", habitat: "astral", tier: "uncommon", line: "Cursola" },
  { name: "Sirfetch'd", habitat: "twilight", tier: "uncommon", line: "Sirfetch'd" },
  { name: "Mr. Rime", habitat: "stormfire", tier: "common", line: "Mime & Mr. Rime" },
  { name: "Falinks", habitat: "twilight", tier: "uncommon", line: "Falinks" },
  { name: "Snom", habitat: "stormfire", tier: "common", line: "Snom & Frosmoth" },
  { name: "Eiscue", habitat: "stormfire", tier: "uncommon", line: "Eiscue" },
  { name: "Indeedee", habitat: "astral", tier: "uncommon", line: "Indeedee" },
  { name: "Morpeko", habitat: "stormfire", tier: "uncommon", line: "Morpeko" },
  { name: "Duraludon", habitat: "earthforged", tier: "uncommon", line: "Duraludon" },
  { name: "Dreepy", habitat: "dragonflight", tier: "rare", line: "Dreepy, Drakloak & Dragapult" },
  { name: "Sprigatito", habitat: "verdant", tier: "common", line: "Sprigatito, Floragato & Meowscarada" },
  { name: "Fuecoco", habitat: "stormfire", tier: "common", line: "Fuecoco, Crocalor & Skeledirge" },
  { name: "Quaxly", habitat: "astral", tier: "common", line: "Quaxly, Quaxwell & Quaquaval" },
  { name: "Lechonk", habitat: "earthforged", tier: "common", line: "Lechonk & Oinkologne" },
  { name: "Tarountula", habitat: "verdant", tier: "common", line: "Tarountula & Spidops" },
  { name: "Nymble", habitat: "verdant", tier: "common", line: "Nymble & Lokix" },
  { name: "Pawmi", habitat: "stormfire", tier: "common", line: "Pawmi, Pawmo & Pawmot" },
  { name: "Tandemaus", habitat: "earthforged", tier: "common", line: "Tandemaus & Maushold" },
  { name: "Fidough", habitat: "twilight", tier: "common", line: "Fidough & Dachsbun" },
  { name: "Smoliv", habitat: "verdant", tier: "common", line: "Smoliv, Dolliv & Arboliva" },
  { name: "Squawkabilly", habitat: "earthforged", tier: "uncommon", line: "Squawkabilly" },
  { name: "Nacli", habitat: "dragonflight", tier: "common", line: "Nacli, Naclstack & Garganacl" },
  { name: "Charcadet", habitat: "stormfire", tier: "common", line: "Charcadet, Armarouge & Ceruledge" },
  { name: "Tadbulb", habitat: "stormfire", tier: "common", line: "Tadbulb & Bellibolt" },
  { name: "Wattrel", habitat: "stormfire", tier: "common", line: "Wattrel & Kilowattrel" },
  { name: "Shroodle", habitat: "verdant", tier: "common", line: "Shroodle & Grafaiai" },
  { name: "Toedscool", habitat: "earthforged", tier: "common", line: "Toedscool & Toedscruel" },
  { name: "Klawf", habitat: "dragonflight", tier: "uncommon", line: "Klawf" },
  { name: "Flittle", habitat: "astral", tier: "common", line: "Flittle & Espathra" },
  { name: "Tinkatink", habitat: "twilight", tier: "common", line: "Tinkatink, Tinkatuff & Tinkaton" },
  { name: "Wiglett", habitat: "astral", tier: "common", line: "Wiglett & Wugtrio" },
  { name: "Bombirdier", habitat: "dragonflight", tier: "uncommon", line: "Bombirdier" },
  { name: "Varoom", habitat: "earthforged", tier: "common", line: "Varoom & Revavroom" },
  { name: "Orthworm", habitat: "earthforged", tier: "uncommon", line: "Orthworm" },
  { name: "Glimmet", habitat: "dragonflight", tier: "common", line: "Glimmet & Glimmora" },
  { name: "Greavard", habitat: "astral", tier: "common", line: "Greavard & Houndstone" },
  { name: "Flamigo", habitat: "dragonflight", tier: "uncommon", line: "Flamigo" },
  { name: "Cetoddle", habitat: "stormfire", tier: "common", line: "Cetoddle & Cetitan" },
  { name: "Dondozo", habitat: "astral", tier: "uncommon", line: "Dondozo" },
  { name: "Tatsugiri", habitat: "dragonflight", tier: "uncommon", line: "Tatsugiri" },
  { name: "Clodsire", habitat: "verdant", tier: "uncommon", line: "Clodsire" },
  { name: "Frigibax", habitat: "dragonflight", tier: "rare", line: "Frigibax, Arctibax & Baxcalibur" },
  { name: "Gimmighoul", habitat: "astral", tier: "rare", line: "Gimmighoul & Gholdengo" },
  { name: "Poltchageist", habitat: "verdant", tier: "common", line: "Poltchageist & Sinistcha" },
// END GENERATED SPECIES
];
