/* ============================================================================
 * GO Fest 2026 Scavenger Hunt — event data
 * ============================================================================
 * Hunt rules encoded here:
 *   - The hunt runs TWICE: a fresh set of tasks each event day, with separate
 *     progress. Day 1 = Saturday's habitats, Day 2 = Sunday's habitats.
 *   - Each day a trainer gets exactly FOUR tasks:
 *       1. Catch N [species]  (N random 5–26, re-rolled with the task)  (rerollable, once)
 *       2. Obtain 1 shiny [species]              (rerollable, once — catch OR trade)
 *       3. Catch 1 Mewtwo                        (fixed)
 *       4. High five your Community Ambassador   (fixed, just for fun)
 *     → two rerolls per day, four for the weekend.
 *   - Each day only counts its first two habitat blocks (10am–4pm); the final
 *     4pm–7pm block is cut so a giveaway can run before the day ends.
 *   - Species pool: every Pokémon FOUND IN THE WILD in Pokémon GO that isn't
 *     Legendary, Mythical, or an Ultra Beast. Species obtainable only from
 *     eggs, raids, evolution, or research (e.g. Smeargle, Tandemaus) never
 *     appear, and neither do species that would only spawn in the cut 4–7pm
 *     block. A species qualifies for a day if EITHER of its types is among
 *     that day's six featured types, so dual-typed species like Ralts
 *     (Psychic/Fairy) can still qualify (Psychic → Saturday).
 *   - Regional exclusives that can't be caught in Boston, MA (Klefki,
 *     Kangaskhan, Mr. Mime, …) are excluded, as are Ditto, Zorua & Zoroark.
 *   - Tasks target whole evolutionary FAMILIES: babies, evolutions, and
 *     regional forms all count. The `line` string on each card spells that out.
 *   - The four hunted species never repeat across the weekend — every draw and
 *     every reroll excludes everything previously rolled (even species that
 *     were rerolled away).
 *
 * The SPECIES array between the GENERATED markers is produced by
 * `node tools/generate-data.mjs` from PvPoke's Pokémon GO gamemaster —
 * edit the config at the top of that script (Boston exclusions, rarity
 * overrides), rerun it, and bump CACHE_VERSION in sw.js.
 * ==========================================================================*/

const HABITATS = {
  stormfire: {
    name: "Stormfire Peaks",
    time: "10am–1pm",
    types: "Ice · Electric · Fire",
    emoji: "🌋",
    color: "#e8590c",
  },
  astral: {
    name: "Astral Tides",
    time: "1pm–4pm",
    types: "Psychic · Ghost · Water",
    emoji: "🌊",
    color: "#7048e8",
  },
  dragonflight: {
    name: "Dragonflight Summit",
    time: "4pm–7pm",
    types: "Flying · Rock · Dragon",
    emoji: "🐉",
    color: "#0c8599",
  },
  earthforged: {
    name: "Earthforged Domain",
    time: "10am–1pm",
    types: "Ground · Steel · Normal",
    emoji: "⛏️",
    color: "#a87900",
  },
  verdant: {
    name: "Verdant Anomaly",
    time: "1pm–4pm",
    types: "Poison · Bug · Grass",
    emoji: "🌿",
    color: "#2f9e44",
  },
  twilight: {
    name: "Twilight Battlefield",
    time: "4pm–7pm",
    types: "Dark · Fairy · Fighting",
    emoji: "🌙",
    color: "#c2255c",
  },
};

// Which habitat time block each type belongs to (for the card chips).
const TYPE_HABITAT = {
  ice: "stormfire", electric: "stormfire", fire: "stormfire",
  psychic: "astral", ghost: "astral", water: "astral",
  flying: "dragonflight", rock: "dragonflight", dragon: "dragonflight",
  ground: "earthforged", steel: "earthforged", normal: "earthforged",
  poison: "verdant", bug: "verdant", grass: "verdant",
  dark: "twilight", fairy: "twilight", fighting: "twilight",
};

// The two event days. Only the FIRST TWO habitat blocks (10am–4pm) count, so a
// giveaway can run before the day is over — the final 4pm–7pm block is cut, and
// species that would only appear then are excluded. A species can be rolled on
// a day if EITHER of its types is featured in that day's remaining six types.
const DAYS = {
  day1: {
    label: "Saturday",
    date: "Jul 11",
    window: "10am–4pm",
    habitats: ["stormfire", "astral"],
    types: ["ice", "electric", "fire", "psychic", "ghost", "water"],
  },
  day2: {
    label: "Sunday",
    date: "Jul 12",
    window: "10am–4pm",
    habitats: ["earthforged", "verdant"],
    types: ["ground", "steel", "normal", "poison", "bug", "grass"],
  },
};

// Task 1: "Catch N [species]", where N is randomized per deal (and re-rolled
// with the task). Drawn from these rarity tiers only — catching 26 of a
// pseudo-legendary line would be miserable even at GO Fest.
const CATCH_COUNT_MIN = 5;
const CATCH_COUNT_MAX = 26;
const CATCH_TASK_TIERS = ["common", "uncommon"];

// Task 2: "Obtain 1 shiny [species]". One is all it takes, so any tier goes.
const SHINY_TASK_TIERS = ["common", "uncommon", "rare"];

// Tasks 3 & 4, identical for every trainer every day.
const MEWTWO_TASK = {
  type: "mewtwo",
  text: "Catch 1 Mewtwo",
  note: "The exception to the wild-spawn rule! Any Mewtwo counts, including one caught after a Mega Mewtwo X or Y Super Mega Raid.",
};

const HIGHFIVE_TASK = {
  type: "highfive",
  text: "High five your Community Ambassador",
  note: "That's it. That's the task. 🖐️",
};

const SPECIES = [
// BEGIN GENERATED SPECIES (tools/generate-data.mjs) — do not edit by hand
  { name: "Bulbasaur", types: ["grass","poison"], tier: "common", line: "Bulbasaur, Ivysaur & Venusaur" },
  { name: "Charmander", types: ["fire"], tier: "common", line: "Charmander, Charmeleon & Charizard" },
  { name: "Squirtle", types: ["water"], tier: "common", line: "Squirtle, Wartortle & Blastoise" },
  { name: "Caterpie", types: ["bug"], tier: "common", line: "Caterpie, Metapod & Butterfree" },
  { name: "Weedle", types: ["bug","poison"], tier: "common", line: "Weedle, Kakuna & Beedrill" },
  { name: "Pidgey", types: ["normal","flying"], tier: "common", line: "Pidgey, Pidgeotto & Pidgeot" },
  { name: "Rattata", types: ["normal"], tier: "common", line: "Rattata & Raticate — any form" },
  { name: "Spearow", types: ["normal","flying"], tier: "common", line: "Spearow & Fearow" },
  { name: "Ekans", types: ["poison"], tier: "common", line: "Ekans & Arbok" },
  { name: "Pikachu", types: ["electric"], tier: "common", line: "Pikachu, Raichu & Pichu — any form" },
  { name: "Sandshrew", types: ["ground"], tier: "common", line: "Sandshrew & Sandslash — any form" },
  { name: "Nidoran Female", types: ["poison"], tier: "common", line: "Nidoran Female, Nidorina & Nidoqueen" },
  { name: "Nidoran Male", types: ["poison"], tier: "common", line: "Nidoran Male, Nidorino & Nidoking" },
  { name: "Clefairy", types: ["fairy"], tier: "common", line: "Clefairy, Clefable & Cleffa" },
  { name: "Vulpix", types: ["fire"], tier: "common", line: "Vulpix & Ninetales — any form" },
  { name: "Jigglypuff", types: ["normal","fairy"], tier: "common", line: "Jigglypuff, Wigglytuff & Igglybuff" },
  { name: "Zubat", types: ["poison","flying"], tier: "common", line: "Zubat, Golbat & Crobat" },
  { name: "Oddish", types: ["grass","poison"], tier: "common", line: "Oddish, Gloom, Vileplume & Bellossom" },
  { name: "Paras", types: ["bug","grass"], tier: "common", line: "Paras & Parasect" },
  { name: "Venonat", types: ["bug","poison"], tier: "common", line: "Venonat & Venomoth" },
  { name: "Diglett", types: ["ground"], tier: "common", line: "Diglett & Dugtrio — any form" },
  { name: "Meowth", types: ["normal"], tier: "common", line: "Meowth, Persian & Perrserker — any form" },
  { name: "Psyduck", types: ["water"], tier: "common", line: "Psyduck & Golduck" },
  { name: "Mankey", types: ["fighting"], tier: "common", line: "Mankey, Primeape & Annihilape" },
  { name: "Growlithe", types: ["fire"], tier: "common", line: "Growlithe & Arcanine — any form" },
  { name: "Poliwag", types: ["water"], tier: "common", line: "Poliwag, Poliwhirl, Poliwrath & Politoed" },
  { name: "Abra", types: ["psychic"], tier: "common", line: "Abra, Kadabra & Alakazam" },
  { name: "Machop", types: ["fighting"], tier: "common", line: "Machop, Machoke & Machamp" },
  { name: "Bellsprout", types: ["grass","poison"], tier: "common", line: "Bellsprout, Weepinbell & Victreebel" },
  { name: "Tentacool", types: ["water","poison"], tier: "common", line: "Tentacool & Tentacruel" },
  { name: "Geodude", types: ["rock","ground"], tier: "common", line: "Geodude, Graveler & Golem — any form" },
  { name: "Ponyta", types: ["fire"], tier: "common", line: "Ponyta & Rapidash — any form" },
  { name: "Slowpoke", types: ["water","psychic"], tier: "common", line: "Slowpoke, Slowbro & Slowking — any form" },
  { name: "Magnemite", types: ["electric","steel"], tier: "common", line: "Magnemite, Magneton & Magnezone" },
  { name: "Doduo", types: ["normal","flying"], tier: "common", line: "Doduo & Dodrio" },
  { name: "Seel", types: ["water"], tier: "common", line: "Seel & Dewgong" },
  { name: "Grimer", types: ["poison"], tier: "common", line: "Grimer & Muk — any form" },
  { name: "Shellder", types: ["water"], tier: "common", line: "Shellder & Cloyster" },
  { name: "Gastly", types: ["ghost","poison"], tier: "common", line: "Gastly, Haunter & Gengar" },
  { name: "Onix", types: ["rock","ground"], tier: "common", line: "Onix & Steelix" },
  { name: "Drowzee", types: ["psychic"], tier: "common", line: "Drowzee & Hypno" },
  { name: "Krabby", types: ["water"], tier: "common", line: "Krabby & Kingler" },
  { name: "Voltorb", types: ["electric"], tier: "common", line: "Voltorb & Electrode — any form" },
  { name: "Exeggcute", types: ["grass","psychic"], tier: "common", line: "Exeggcute & Exeggutor — any form" },
  { name: "Cubone", types: ["ground"], tier: "common", line: "Cubone & Marowak — any form" },
  { name: "Hitmonlee", types: ["fighting"], tier: "common", line: "Hitmonlee, Hitmonchan, Tyrogue & Hitmontop" },
  { name: "Lickitung", types: ["normal"], tier: "common", line: "Lickitung & Lickilicky" },
  { name: "Koffing", types: ["poison"], tier: "common", line: "Koffing & Weezing — any form" },
  { name: "Rhyhorn", types: ["ground","rock"], tier: "common", line: "Rhyhorn, Rhydon & Rhyperior" },
  { name: "Chansey", types: ["normal"], tier: "rare", line: "Chansey, Blissey & Happiny" },
  { name: "Tangela", types: ["grass"], tier: "common", line: "Tangela & Tangrowth" },
  { name: "Horsea", types: ["water"], tier: "common", line: "Horsea, Seadra & Kingdra" },
  { name: "Goldeen", types: ["water"], tier: "common", line: "Goldeen & Seaking" },
  { name: "Staryu", types: ["water"], tier: "common", line: "Staryu & Starmie" },
  { name: "Scyther", types: ["bug","flying"], tier: "common", line: "Scyther, Scizor & Kleavor" },
  { name: "Jynx", types: ["ice","psychic"], tier: "common", line: "Jynx & Smoochum" },
  { name: "Electabuzz", types: ["electric"], tier: "common", line: "Electabuzz, Elekid & Electivire" },
  { name: "Magmar", types: ["fire"], tier: "common", line: "Magmar, Magby & Magmortar" },
  { name: "Pinsir", types: ["bug"], tier: "uncommon", line: "Pinsir" },
  { name: "Tauros", types: ["normal"], tier: "uncommon", line: "Tauros — any form" },
  { name: "Magikarp", types: ["water"], tier: "common", line: "Magikarp & Gyarados" },
  { name: "Lapras", types: ["water","ice"], tier: "uncommon", line: "Lapras" },
  { name: "Eevee", types: ["normal"], tier: "common", line: "Eevee, Vaporeon, Jolteon, Flareon, Espeon, Umbreon, Leafeon, Glaceon & Sylveon" },
  { name: "Porygon", types: ["normal"], tier: "common", line: "Porygon, Porygon2 & Porygon-Z" },
  { name: "Omanyte", types: ["rock","water"], tier: "uncommon", line: "Omanyte & Omastar" },
  { name: "Kabuto", types: ["rock","water"], tier: "uncommon", line: "Kabuto & Kabutops" },
  { name: "Aerodactyl", types: ["rock","flying"], tier: "uncommon", line: "Aerodactyl" },
  { name: "Snorlax", types: ["normal"], tier: "uncommon", line: "Snorlax & Munchlax" },
  { name: "Dratini", types: ["dragon"], tier: "rare", line: "Dratini, Dragonair & Dragonite" },
  { name: "Chikorita", types: ["grass"], tier: "common", line: "Chikorita, Bayleef & Meganium" },
  { name: "Cyndaquil", types: ["fire"], tier: "common", line: "Cyndaquil, Quilava & Typhlosion — any form" },
  { name: "Totodile", types: ["water"], tier: "common", line: "Totodile, Croconaw & Feraligatr" },
  { name: "Sentret", types: ["normal"], tier: "common", line: "Sentret & Furret" },
  { name: "Hoothoot", types: ["normal","flying"], tier: "common", line: "Hoothoot & Noctowl" },
  { name: "Ledyba", types: ["bug","flying"], tier: "common", line: "Ledyba & Ledian" },
  { name: "Spinarak", types: ["bug","poison"], tier: "common", line: "Spinarak & Ariados" },
  { name: "Chinchou", types: ["water","electric"], tier: "common", line: "Chinchou & Lanturn" },
  { name: "Natu", types: ["psychic","flying"], tier: "common", line: "Natu & Xatu" },
  { name: "Mareep", types: ["electric"], tier: "common", line: "Mareep, Flaaffy & Ampharos" },
  { name: "Marill", types: ["water","fairy"], tier: "common", line: "Marill, Azumarill & Azurill" },
  { name: "Sudowoodo", types: ["rock"], tier: "common", line: "Sudowoodo & Bonsly" },
  { name: "Hoppip", types: ["grass","flying"], tier: "common", line: "Hoppip, Skiploom & Jumpluff" },
  { name: "Aipom", types: ["normal"], tier: "common", line: "Aipom & Ambipom" },
  { name: "Sunkern", types: ["grass"], tier: "common", line: "Sunkern & Sunflora" },
  { name: "Yanma", types: ["bug","flying"], tier: "common", line: "Yanma & Yanmega" },
  { name: "Wooper", types: ["water","ground"], tier: "common", line: "Wooper & Quagsire — any form" },
  { name: "Murkrow", types: ["dark","flying"], tier: "common", line: "Murkrow & Honchkrow" },
  { name: "Misdreavus", types: ["ghost"], tier: "common", line: "Misdreavus & Mismagius" },
  { name: "Unown", types: ["psychic"], tier: "rare", line: "Unown" },
  { name: "Wobbuffet", types: ["psychic"], tier: "common", line: "Wobbuffet & Wynaut" },
  { name: "Girafarig", types: ["normal","psychic"], tier: "uncommon", line: "Girafarig" },
  { name: "Pineco", types: ["bug"], tier: "common", line: "Pineco & Forretress" },
  { name: "Dunsparce", types: ["normal"], tier: "common", line: "Dunsparce & Dudunsparce" },
  { name: "Gligar", types: ["ground","flying"], tier: "common", line: "Gligar & Gliscor" },
  { name: "Snubbull", types: ["fairy"], tier: "common", line: "Snubbull & Granbull" },
  { name: "Qwilfish", types: ["water","poison"], tier: "common", line: "Qwilfish & Overqwil — any form" },
  { name: "Shuckle", types: ["bug","rock"], tier: "uncommon", line: "Shuckle" },
  { name: "Sneasel", types: ["dark","ice"], tier: "common", line: "Sneasel, Weavile & Sneasler — any form" },
  { name: "Teddiursa", types: ["normal"], tier: "common", line: "Teddiursa, Ursaring & Ursaluna" },
  { name: "Slugma", types: ["fire"], tier: "common", line: "Slugma & Magcargo" },
  { name: "Swinub", types: ["ice","ground"], tier: "common", line: "Swinub, Piloswine & Mamoswine" },
  { name: "Remoraid", types: ["water"], tier: "common", line: "Remoraid & Octillery" },
  { name: "Delibird", types: ["ice","flying"], tier: "uncommon", line: "Delibird" },
  { name: "Mantine", types: ["water","flying"], tier: "common", line: "Mantine & Mantyke" },
  { name: "Skarmory", types: ["steel","flying"], tier: "uncommon", line: "Skarmory" },
  { name: "Houndour", types: ["dark","fire"], tier: "common", line: "Houndour & Houndoom" },
  { name: "Phanpy", types: ["ground"], tier: "common", line: "Phanpy & Donphan" },
  { name: "Stantler", types: ["normal"], tier: "common", line: "Stantler & Wyrdeer" },
  { name: "Miltank", types: ["normal"], tier: "uncommon", line: "Miltank" },
  { name: "Larvitar", types: ["rock","ground"], tier: "rare", line: "Larvitar, Pupitar & Tyranitar" },
  { name: "Treecko", types: ["grass"], tier: "common", line: "Treecko, Grovyle & Sceptile" },
  { name: "Torchic", types: ["fire"], tier: "common", line: "Torchic, Combusken & Blaziken" },
  { name: "Mudkip", types: ["water"], tier: "common", line: "Mudkip, Marshtomp & Swampert" },
  { name: "Poochyena", types: ["dark"], tier: "common", line: "Poochyena & Mightyena" },
  { name: "Zigzagoon", types: ["normal"], tier: "common", line: "Zigzagoon, Linoone & Obstagoon — any form" },
  { name: "Wurmple", types: ["bug"], tier: "common", line: "Wurmple, Silcoon, Beautifly, Cascoon & Dustox" },
  { name: "Lotad", types: ["water","grass"], tier: "common", line: "Lotad, Lombre & Ludicolo" },
  { name: "Seedot", types: ["grass"], tier: "common", line: "Seedot, Nuzleaf & Shiftry" },
  { name: "Taillow", types: ["normal","flying"], tier: "common", line: "Taillow & Swellow" },
  { name: "Wingull", types: ["water","flying"], tier: "common", line: "Wingull & Pelipper" },
  { name: "Ralts", types: ["psychic","fairy"], tier: "common", line: "Ralts, Kirlia, Gardevoir & Gallade" },
  { name: "Surskit", types: ["bug","water"], tier: "common", line: "Surskit & Masquerain" },
  { name: "Shroomish", types: ["grass"], tier: "common", line: "Shroomish & Breloom" },
  { name: "Slakoth", types: ["normal"], tier: "common", line: "Slakoth, Vigoroth & Slaking" },
  { name: "Nincada", types: ["bug","ground"], tier: "common", line: "Nincada & Ninjask" },
  { name: "Whismur", types: ["normal"], tier: "common", line: "Whismur, Loudred & Exploud" },
  { name: "Makuhita", types: ["fighting"], tier: "common", line: "Makuhita & Hariyama" },
  { name: "Nosepass", types: ["rock"], tier: "common", line: "Nosepass & Probopass" },
  { name: "Skitty", types: ["normal"], tier: "common", line: "Skitty & Delcatty" },
  { name: "Sableye", types: ["dark","ghost"], tier: "uncommon", line: "Sableye" },
  { name: "Mawile", types: ["steel","fairy"], tier: "uncommon", line: "Mawile" },
  { name: "Aron", types: ["steel","rock"], tier: "common", line: "Aron, Lairon & Aggron" },
  { name: "Meditite", types: ["fighting","psychic"], tier: "common", line: "Meditite & Medicham" },
  { name: "Electrike", types: ["electric"], tier: "common", line: "Electrike & Manectric" },
  { name: "Plusle", types: ["electric"], tier: "uncommon", line: "Plusle" },
  { name: "Minun", types: ["electric"], tier: "uncommon", line: "Minun" },
  { name: "Illumise", types: ["bug"], tier: "uncommon", line: "Illumise" },
  { name: "Roselia", types: ["grass","poison"], tier: "common", line: "Roselia, Budew & Roserade" },
  { name: "Gulpin", types: ["poison"], tier: "common", line: "Gulpin & Swalot" },
  { name: "Carvanha", types: ["water","dark"], tier: "common", line: "Carvanha & Sharpedo" },
  { name: "Wailmer", types: ["water"], tier: "common", line: "Wailmer & Wailord" },
  { name: "Numel", types: ["fire","ground"], tier: "common", line: "Numel & Camerupt" },
  { name: "Spoink", types: ["psychic"], tier: "common", line: "Spoink & Grumpig" },
  { name: "Spinda", types: ["normal"], tier: "uncommon", line: "Spinda" },
  { name: "Trapinch", types: ["ground"], tier: "common", line: "Trapinch, Vibrava & Flygon" },
  { name: "Cacnea", types: ["grass"], tier: "common", line: "Cacnea & Cacturne" },
  { name: "Swablu", types: ["normal","flying"], tier: "common", line: "Swablu & Altaria" },
  { name: "Seviper", types: ["poison"], tier: "uncommon", line: "Seviper" },
  { name: "Lunatone", types: ["rock","psychic"], tier: "uncommon", line: "Lunatone" },
  { name: "Barboach", types: ["water","ground"], tier: "common", line: "Barboach & Whiscash" },
  { name: "Corphish", types: ["water"], tier: "common", line: "Corphish & Crawdaunt" },
  { name: "Baltoy", types: ["ground","psychic"], tier: "common", line: "Baltoy & Claydol" },
  { name: "Lileep", types: ["rock","grass"], tier: "uncommon", line: "Lileep & Cradily" },
  { name: "Anorith", types: ["rock","bug"], tier: "uncommon", line: "Anorith & Armaldo" },
  { name: "Feebas", types: ["water"], tier: "common", line: "Feebas & Milotic" },
  { name: "Castform", types: ["normal"], tier: "uncommon", line: "Castform" },
  { name: "Kecleon", types: ["normal"], tier: "uncommon", line: "Kecleon" },
  { name: "Shuppet", types: ["ghost"], tier: "common", line: "Shuppet & Banette" },
  { name: "Duskull", types: ["ghost"], tier: "common", line: "Duskull, Dusclops & Dusknoir" },
  { name: "Chimecho", types: ["psychic"], tier: "common", line: "Chimecho & Chingling" },
  { name: "Absol", types: ["dark"], tier: "uncommon", line: "Absol" },
  { name: "Snorunt", types: ["ice"], tier: "common", line: "Snorunt, Glalie & Froslass" },
  { name: "Spheal", types: ["ice","water"], tier: "common", line: "Spheal, Sealeo & Walrein" },
  { name: "Clamperl", types: ["water"], tier: "common", line: "Clamperl, Huntail & Gorebyss" },
  { name: "Luvdisc", types: ["water"], tier: "uncommon", line: "Luvdisc" },
  { name: "Bagon", types: ["dragon"], tier: "rare", line: "Bagon, Shelgon & Salamence" },
  { name: "Beldum", types: ["steel","psychic"], tier: "rare", line: "Beldum, Metang & Metagross" },
  { name: "Turtwig", types: ["grass"], tier: "common", line: "Turtwig, Grotle & Torterra" },
  { name: "Chimchar", types: ["fire"], tier: "common", line: "Chimchar, Monferno & Infernape" },
  { name: "Piplup", types: ["water"], tier: "common", line: "Piplup, Prinplup & Empoleon" },
  { name: "Starly", types: ["normal","flying"], tier: "common", line: "Starly, Staravia & Staraptor" },
  { name: "Bidoof", types: ["normal"], tier: "common", line: "Bidoof & Bibarel" },
  { name: "Kricketot", types: ["bug"], tier: "common", line: "Kricketot & Kricketune" },
  { name: "Shinx", types: ["electric"], tier: "common", line: "Shinx, Luxio & Luxray" },
  { name: "Cranidos", types: ["rock"], tier: "uncommon", line: "Cranidos & Rampardos" },
  { name: "Shieldon", types: ["rock","steel"], tier: "uncommon", line: "Shieldon & Bastiodon" },
  { name: "Burmy", types: ["bug"], tier: "common", line: "Burmy, Wormadam & Mothim" },
  { name: "Combee", types: ["bug","flying"], tier: "common", line: "Combee & Vespiquen" },
  { name: "Buizel", types: ["water"], tier: "common", line: "Buizel & Floatzel" },
  { name: "Cherubi", types: ["grass"], tier: "common", line: "Cherubi & Cherrim" },
  { name: "Shellos", types: ["water"], tier: "uncommon", line: "Shellos" },
  { name: "Gastrodon", types: ["water","ground"], tier: "uncommon", line: "Gastrodon" },
  { name: "Drifloon", types: ["ghost","flying"], tier: "common", line: "Drifloon & Drifblim" },
  { name: "Buneary", types: ["normal"], tier: "common", line: "Buneary & Lopunny" },
  { name: "Glameow", types: ["normal"], tier: "common", line: "Glameow & Purugly" },
  { name: "Stunky", types: ["poison","dark"], tier: "common", line: "Stunky & Skuntank" },
  { name: "Bronzor", types: ["steel","psychic"], tier: "common", line: "Bronzor & Bronzong" },
  { name: "Spiritomb", types: ["ghost","dark"], tier: "uncommon", line: "Spiritomb" },
  { name: "Gible", types: ["dragon","ground"], tier: "rare", line: "Gible, Gabite & Garchomp" },
  { name: "Hippopotas", types: ["ground"], tier: "common", line: "Hippopotas & Hippowdon" },
  { name: "Skorupi", types: ["poison","bug"], tier: "common", line: "Skorupi & Drapion" },
  { name: "Croagunk", types: ["poison","fighting"], tier: "common", line: "Croagunk & Toxicroak" },
  { name: "Finneon", types: ["water"], tier: "common", line: "Finneon & Lumineon" },
  { name: "Snover", types: ["grass","ice"], tier: "common", line: "Snover & Abomasnow" },
  { name: "Snivy", types: ["grass"], tier: "common", line: "Snivy, Servine & Serperior" },
  { name: "Tepig", types: ["fire"], tier: "common", line: "Tepig, Pignite & Emboar" },
  { name: "Oshawott", types: ["water"], tier: "common", line: "Oshawott, Dewott & Samurott — any form" },
  { name: "Patrat", types: ["normal"], tier: "common", line: "Patrat & Watchog" },
  { name: "Lillipup", types: ["normal"], tier: "common", line: "Lillipup, Herdier & Stoutland" },
  { name: "Purrloin", types: ["dark"], tier: "common", line: "Purrloin & Liepard" },
  { name: "Simisage", types: ["grass"], tier: "uncommon", line: "Simisage" },
  { name: "Simisear", types: ["fire"], tier: "uncommon", line: "Simisear" },
  { name: "Panpour", types: ["water"], tier: "common", line: "Panpour & Simipour" },
  { name: "Munna", types: ["psychic"], tier: "common", line: "Munna & Musharna" },
  { name: "Pidove", types: ["normal","flying"], tier: "common", line: "Pidove, Tranquill & Unfezant" },
  { name: "Blitzle", types: ["electric"], tier: "common", line: "Blitzle & Zebstrika" },
  { name: "Roggenrola", types: ["rock"], tier: "common", line: "Roggenrola, Boldore & Gigalith" },
  { name: "Woobat", types: ["psychic","flying"], tier: "common", line: "Woobat & Swoobat" },
  { name: "Drilbur", types: ["ground"], tier: "common", line: "Drilbur & Excadrill" },
  { name: "Audino", types: ["normal"], tier: "uncommon", line: "Audino" },
  { name: "Timburr", types: ["fighting"], tier: "common", line: "Timburr, Gurdurr & Conkeldurr" },
  { name: "Tympole", types: ["water"], tier: "common", line: "Tympole, Palpitoad & Seismitoad" },
  { name: "Throh", types: ["fighting"], tier: "uncommon", line: "Throh" },
  { name: "Sawk", types: ["fighting"], tier: "uncommon", line: "Sawk" },
  { name: "Sewaddle", types: ["bug","grass"], tier: "common", line: "Sewaddle, Swadloon & Leavanny" },
  { name: "Venipede", types: ["bug","poison"], tier: "common", line: "Venipede, Whirlipede & Scolipede" },
  { name: "Cottonee", types: ["grass","fairy"], tier: "common", line: "Cottonee & Whimsicott" },
  { name: "Petilil", types: ["grass"], tier: "common", line: "Petilil & Lilligant — any form" },
  { name: "Basculin", types: ["water"], tier: "uncommon", line: "Basculin" },
  { name: "Sandile", types: ["ground","dark"], tier: "common", line: "Sandile, Krokorok & Krookodile" },
  { name: "Darumaka", types: ["fire"], tier: "common", line: "Darumaka & Darmanitan — any form" },
  { name: "Dwebble", types: ["bug","rock"], tier: "common", line: "Dwebble & Crustle" },
  { name: "Scraggy", types: ["dark","fighting"], tier: "common", line: "Scraggy & Scrafty" },
  { name: "Yamask", types: ["ghost"], tier: "common", line: "Yamask, Cofagrigus & Runerigus — any form" },
  { name: "Tirtouga", types: ["water","rock"], tier: "uncommon", line: "Tirtouga & Carracosta" },
  { name: "Archen", types: ["rock","flying"], tier: "uncommon", line: "Archen & Archeops" },
  { name: "Trubbish", types: ["poison"], tier: "common", line: "Trubbish & Garbodor" },
  { name: "Minccino", types: ["normal"], tier: "common", line: "Minccino & Cinccino" },
  { name: "Gothita", types: ["psychic"], tier: "common", line: "Gothita, Gothorita & Gothitelle" },
  { name: "Solosis", types: ["psychic"], tier: "common", line: "Solosis, Duosion & Reuniclus" },
  { name: "Ducklett", types: ["water","flying"], tier: "common", line: "Ducklett & Swanna" },
  { name: "Vanillite", types: ["ice"], tier: "common", line: "Vanillite, Vanillish & Vanilluxe" },
  { name: "Deerling", types: ["normal","grass"], tier: "common", line: "Deerling & Sawsbuck" },
  { name: "Emolga", types: ["electric","flying"], tier: "uncommon", line: "Emolga" },
  { name: "Karrablast", types: ["bug"], tier: "common", line: "Karrablast & Escavalier" },
  { name: "Foongus", types: ["grass","poison"], tier: "common", line: "Foongus & Amoonguss" },
  { name: "Frillish", types: ["water","ghost"], tier: "common", line: "Frillish & Jellicent" },
  { name: "Alomomola", types: ["water"], tier: "uncommon", line: "Alomomola" },
  { name: "Joltik", types: ["bug","electric"], tier: "common", line: "Joltik & Galvantula" },
  { name: "Ferroseed", types: ["grass","steel"], tier: "common", line: "Ferroseed & Ferrothorn" },
  { name: "Klink", types: ["steel"], tier: "common", line: "Klink, Klang & Klinklang" },
  { name: "Tynamo", types: ["electric"], tier: "common", line: "Tynamo, Eelektrik & Eelektross" },
  { name: "Elgyem", types: ["psychic"], tier: "common", line: "Elgyem & Beheeyem" },
  { name: "Litwick", types: ["ghost","fire"], tier: "common", line: "Litwick, Lampent & Chandelure" },
  { name: "Axew", types: ["dragon"], tier: "rare", line: "Axew, Fraxure & Haxorus" },
  { name: "Cubchoo", types: ["ice"], tier: "common", line: "Cubchoo & Beartic" },
  { name: "Cryogonal", types: ["ice"], tier: "uncommon", line: "Cryogonal" },
  { name: "Shelmet", types: ["bug"], tier: "common", line: "Shelmet & Accelgor" },
  { name: "Stunfisk", types: ["ground","electric"], tier: "uncommon", line: "Stunfisk — any form" },
  { name: "Mienfoo", types: ["fighting"], tier: "common", line: "Mienfoo & Mienshao" },
  { name: "Druddigon", types: ["dragon"], tier: "uncommon", line: "Druddigon" },
  { name: "Golett", types: ["ground","ghost"], tier: "common", line: "Golett & Golurk" },
  { name: "Pawniard", types: ["dark","steel"], tier: "common", line: "Pawniard, Bisharp & Kingambit" },
  { name: "Rufflet", types: ["normal","flying"], tier: "common", line: "Rufflet & Braviary — any form" },
  { name: "Vullaby", types: ["dark","flying"], tier: "common", line: "Vullaby & Mandibuzz" },
  { name: "Heatmor", types: ["fire"], tier: "uncommon", line: "Heatmor" },
  { name: "Deino", types: ["dark","dragon"], tier: "rare", line: "Deino, Zweilous & Hydreigon" },
  { name: "Chespin", types: ["grass"], tier: "common", line: "Chespin, Quilladin & Chesnaught" },
  { name: "Fennekin", types: ["fire"], tier: "common", line: "Fennekin, Braixen & Delphox" },
  { name: "Froakie", types: ["water"], tier: "common", line: "Froakie, Frogadier & Greninja" },
  { name: "Bunnelby", types: ["normal"], tier: "common", line: "Bunnelby & Diggersby" },
  { name: "Fletchling", types: ["normal","flying"], tier: "common", line: "Fletchling, Fletchinder & Talonflame" },
  { name: "Scatterbug", types: ["bug"], tier: "common", line: "Scatterbug & Vivillon" },
  { name: "Litleo", types: ["fire","normal"], tier: "common", line: "Litleo & Pyroar" },
  { name: "Flabebe", types: ["fairy"], tier: "common", line: "Flabebe, Floette & Florges" },
  { name: "Skiddo", types: ["grass"], tier: "common", line: "Skiddo & Gogoat" },
  { name: "Pancham", types: ["fighting"], tier: "common", line: "Pancham & Pangoro" },
  { name: "Furfrou", types: ["normal"], tier: "uncommon", line: "Furfrou" },
  { name: "Espurr", types: ["psychic"], tier: "common", line: "Espurr & Meowstic" },
  { name: "Honedge", types: ["steel","ghost"], tier: "common", line: "Honedge, Doublade & Aegislash" },
  { name: "Spritzee", types: ["fairy"], tier: "common", line: "Spritzee & Aromatisse" },
  { name: "Swirlix", types: ["fairy"], tier: "common", line: "Swirlix & Slurpuff" },
  { name: "Inkay", types: ["dark","psychic"], tier: "common", line: "Inkay & Malamar" },
  { name: "Binacle", types: ["rock","water"], tier: "common", line: "Binacle & Barbaracle" },
  { name: "Skrelp", types: ["poison","water"], tier: "common", line: "Skrelp & Dragalge" },
  { name: "Clauncher", types: ["water"], tier: "common", line: "Clauncher & Clawitzer" },
  { name: "Helioptile", types: ["electric","normal"], tier: "common", line: "Helioptile & Heliolisk" },
  { name: "Tyrunt", types: ["rock","dragon"], tier: "uncommon", line: "Tyrunt & Tyrantrum" },
  { name: "Amaura", types: ["rock","ice"], tier: "uncommon", line: "Amaura & Aurorus" },
  { name: "Dedenne", types: ["electric","fairy"], tier: "uncommon", line: "Dedenne" },
  { name: "Carbink", types: ["rock","fairy"], tier: "uncommon", line: "Carbink" },
  { name: "Goomy", types: ["dragon"], tier: "rare", line: "Goomy, Sliggoo & Goodra" },
  { name: "Phantump", types: ["ghost","grass"], tier: "common", line: "Phantump & Trevenant" },
  { name: "Pumpkaboo", types: ["ghost","grass"], tier: "common", line: "Pumpkaboo & Gourgeist" },
  { name: "Bergmite", types: ["ice"], tier: "common", line: "Bergmite & Avalugg — any form" },
  { name: "Noibat", types: ["flying","dragon"], tier: "rare", line: "Noibat & Noivern" },
  { name: "Rowlet", types: ["grass","flying"], tier: "common", line: "Rowlet, Dartrix & Decidueye" },
  { name: "Litten", types: ["fire"], tier: "common", line: "Litten, Torracat & Incineroar" },
  { name: "Popplio", types: ["water"], tier: "common", line: "Popplio, Brionne & Primarina" },
  { name: "Pikipek", types: ["normal","flying"], tier: "common", line: "Pikipek, Trumbeak & Toucannon" },
  { name: "Yungoos", types: ["normal"], tier: "common", line: "Yungoos & Gumshoos" },
  { name: "Grubbin", types: ["bug"], tier: "common", line: "Grubbin, Charjabug & Vikavolt" },
  { name: "Crabrawler", types: ["fighting"], tier: "common", line: "Crabrawler & Crabominable" },
  { name: "Oricorio", types: ["psychic","flying"], tier: "uncommon", line: "Oricorio" },
  { name: "Cutiefly", types: ["bug","fairy"], tier: "common", line: "Cutiefly & Ribombee" },
  { name: "Rockruff", types: ["rock"], tier: "common", line: "Rockruff & Lycanroc" },
  { name: "Mareanie", types: ["poison","water"], tier: "common", line: "Mareanie & Toxapex" },
  { name: "Mudbray", types: ["ground"], tier: "common", line: "Mudbray & Mudsdale" },
  { name: "Dewpider", types: ["water","bug"], tier: "common", line: "Dewpider & Araquanid" },
  { name: "Fomantis", types: ["grass"], tier: "common", line: "Fomantis & Lurantis" },
  { name: "Morelull", types: ["grass","fairy"], tier: "common", line: "Morelull & Shiinotic" },
  { name: "Salandit", types: ["poison","fire"], tier: "common", line: "Salandit & Salazzle" },
  { name: "Stufful", types: ["normal","fighting"], tier: "common", line: "Stufful & Bewear" },
  { name: "Bounsweet", types: ["grass"], tier: "common", line: "Bounsweet, Steenee & Tsareena" },
  { name: "Oranguru", types: ["normal","psychic"], tier: "uncommon", line: "Oranguru" },
  { name: "Passimian", types: ["fighting"], tier: "uncommon", line: "Passimian" },
  { name: "Wimpod", types: ["bug","water"], tier: "common", line: "Wimpod & Golisopod" },
  { name: "Sandygast", types: ["ghost","ground"], tier: "common", line: "Sandygast & Palossand" },
  { name: "Komala", types: ["normal"], tier: "uncommon", line: "Komala" },
  { name: "Turtonator", types: ["fire","dragon"], tier: "uncommon", line: "Turtonator" },
  { name: "Togedemaru", types: ["electric","steel"], tier: "uncommon", line: "Togedemaru" },
  { name: "Mimikyu", types: ["ghost","fairy"], tier: "uncommon", line: "Mimikyu" },
  { name: "Bruxish", types: ["water","psychic"], tier: "uncommon", line: "Bruxish" },
  { name: "Drampa", types: ["normal","dragon"], tier: "uncommon", line: "Drampa" },
  { name: "Dhelmise", types: ["ghost","grass"], tier: "uncommon", line: "Dhelmise" },
  { name: "Jangmo-o", types: ["dragon"], tier: "rare", line: "Jangmo-o, Hakamo-o & Kommo-o" },
  { name: "Grookey", types: ["grass"], tier: "common", line: "Grookey, Thwackey & Rillaboom" },
  { name: "Scorbunny", types: ["fire"], tier: "common", line: "Scorbunny, Raboot & Cinderace" },
  { name: "Sobble", types: ["water"], tier: "common", line: "Sobble, Drizzile & Inteleon" },
  { name: "Skwovet", types: ["normal"], tier: "common", line: "Skwovet & Greedent" },
  { name: "Rookidee", types: ["flying"], tier: "common", line: "Rookidee, Corvisquire & Corviknight" },
  { name: "Blipbug", types: ["bug"], tier: "common", line: "Blipbug, Dottler & Orbeetle" },
  { name: "Nickit", types: ["dark"], tier: "common", line: "Nickit & Thievul" },
  { name: "Gossifleur", types: ["grass"], tier: "common", line: "Gossifleur & Eldegoss" },
  { name: "Wooloo", types: ["normal"], tier: "common", line: "Wooloo & Dubwool" },
  { name: "Yamper", types: ["electric"], tier: "common", line: "Yamper & Boltund" },
  { name: "Rolycoly", types: ["rock"], tier: "common", line: "Rolycoly, Carkol & Coalossal" },
  { name: "Applin", types: ["grass","dragon"], tier: "common", line: "Applin, Flapple, Appletun, Dipplin & Hydrapple" },
  { name: "Silicobra", types: ["ground"], tier: "common", line: "Silicobra & Sandaconda" },
  { name: "Sizzlipede", types: ["fire","bug"], tier: "common", line: "Sizzlipede & Centiskorch" },
  { name: "Clobbopus", types: ["fighting"], tier: "common", line: "Clobbopus & Grapploct" },
  { name: "Sinistea", types: ["ghost"], tier: "common", line: "Sinistea & Polteageist" },
  { name: "Hatenna", types: ["psychic"], tier: "common", line: "Hatenna, Hattrem & Hatterene" },
  { name: "Impidimp", types: ["dark","fairy"], tier: "common", line: "Impidimp, Morgrem & Grimmsnarl" },
  { name: "Snom", types: ["ice","bug"], tier: "common", line: "Snom & Frosmoth" },
  { name: "Eiscue", types: ["ice"], tier: "uncommon", line: "Eiscue" },
  { name: "Indeedee", types: ["psychic","normal"], tier: "uncommon", line: "Indeedee" },
  { name: "Morpeko", types: ["electric","dark"], tier: "uncommon", line: "Morpeko" },
  { name: "Dreepy", types: ["dragon","ghost"], tier: "rare", line: "Dreepy, Drakloak & Dragapult" },
  { name: "Sprigatito", types: ["grass"], tier: "common", line: "Sprigatito, Floragato & Meowscarada" },
  { name: "Fuecoco", types: ["fire"], tier: "common", line: "Fuecoco, Crocalor & Skeledirge" },
  { name: "Quaxly", types: ["water"], tier: "common", line: "Quaxly, Quaxwell & Quaquaval" },
  { name: "Lechonk", types: ["normal"], tier: "common", line: "Lechonk & Oinkologne" },
  { name: "Tarountula", types: ["bug"], tier: "common", line: "Tarountula & Spidops" },
  { name: "Nymble", types: ["bug"], tier: "common", line: "Nymble & Lokix" },
  { name: "Pawmi", types: ["electric"], tier: "common", line: "Pawmi, Pawmo & Pawmot" },
  { name: "Fidough", types: ["fairy"], tier: "common", line: "Fidough & Dachsbun" },
  { name: "Smoliv", types: ["grass","normal"], tier: "common", line: "Smoliv, Dolliv & Arboliva" },
  { name: "Squawkabilly", types: ["normal","flying"], tier: "uncommon", line: "Squawkabilly" },
  { name: "Nacli", types: ["rock"], tier: "common", line: "Nacli, Naclstack & Garganacl" },
  { name: "Charcadet", types: ["fire"], tier: "common", line: "Charcadet, Armarouge & Ceruledge" },
  { name: "Tadbulb", types: ["electric"], tier: "common", line: "Tadbulb & Bellibolt" },
  { name: "Wattrel", types: ["electric","flying"], tier: "common", line: "Wattrel & Kilowattrel" },
  { name: "Shroodle", types: ["poison","normal"], tier: "common", line: "Shroodle & Grafaiai" },
  { name: "Toedscool", types: ["ground","grass"], tier: "common", line: "Toedscool & Toedscruel" },
  { name: "Klawf", types: ["rock"], tier: "uncommon", line: "Klawf" },
  { name: "Flittle", types: ["psychic"], tier: "common", line: "Flittle & Espathra" },
  { name: "Tinkatink", types: ["fairy","steel"], tier: "common", line: "Tinkatink, Tinkatuff & Tinkaton" },
  { name: "Wiglett", types: ["water"], tier: "common", line: "Wiglett & Wugtrio" },
  { name: "Bombirdier", types: ["flying","dark"], tier: "uncommon", line: "Bombirdier" },
  { name: "Varoom", types: ["steel","poison"], tier: "common", line: "Varoom & Revavroom" },
  { name: "Orthworm", types: ["steel"], tier: "uncommon", line: "Orthworm" },
  { name: "Glimmet", types: ["rock","poison"], tier: "common", line: "Glimmet & Glimmora" },
  { name: "Greavard", types: ["ghost"], tier: "common", line: "Greavard & Houndstone" },
  { name: "Flamigo", types: ["flying","fighting"], tier: "uncommon", line: "Flamigo" },
  { name: "Cetoddle", types: ["ice"], tier: "common", line: "Cetoddle & Cetitan" },
  { name: "Dondozo", types: ["water"], tier: "uncommon", line: "Dondozo" },
  { name: "Tatsugiri", types: ["dragon","water"], tier: "uncommon", line: "Tatsugiri" },
  { name: "Clodsire", types: ["poison","ground"], tier: "uncommon", line: "Clodsire" },
  { name: "Frigibax", types: ["dragon","ice"], tier: "rare", line: "Frigibax, Arctibax & Baxcalibur" },
  { name: "Poltchageist", types: ["grass","ghost"], tier: "common", line: "Poltchageist & Sinistcha" },
// END GENERATED SPECIES
];
